### ISSUE TITLE
How to find MAC address of tooth brush

### ISSUE THREAD

**Issue by Jimster1** [timodejong95/MMM-BluetoothDevices#3]
Any tips on how to find the MAC address of the toothbrush to add tot the config ?

Thanks
Jim

**Comment by timodejong95** [comment]
Hey @Jimster1,

Sorry for my late reply.

If you haven't figured it out already you can search bluetooth devices with this command:
```bash
hcitool scan
```

I have noted this and I will put this in the documentation, when I got some time.

**Comment by Jimster1** [comment]
I tried this but it does not return anything?


`pi@raspberrypi_MM:~/MagicMirror/modules/MMM-BluetoothDevices $ hcitool scan
Scanning ...
pi@raspberrypi_MM:~/MagicMirror/modules/MMM-BluetoothDevices $
`

**Comment by timodejong95** [comment]
Hey @Jimster1,

My bad, I haven't documentated this part when I build it.

I checked it and what you have to do is use bluetoothctl, run:
```bash
sudo bluetoothctl
```

Then you will see:
```text
Agent registered
[bluetooth]#
```

If you then prompt the following command:
```bash
scan on
```
All bluetooth devices will show in a list. It might take a bit for the bluetooth device to be discovered. You also want to press a button on the toothbrush so the device will send a bluetooth message.

Can you confirm this worked?

**Comment by Jimster1** [comment]
amazing, that worked a treat. Thank you
